version: 0.2

phases:
  install:
    commands:
      # Install Node.js
      # - echo Installing Node.js...
      # - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      # - yum install -y nodejs

      # Install Python dependencies
      - echo "Installing Python & CDK dependencies..."
      - pwd
      - pip install --upgrade pip
      - pip install -r cdk/requirements.txt
      - npm install -g aws-cdk

  pre_build:
    commands:
      - echo "Building React App..."
      - pwd
      - ls -la
      - cd frontend/code
      - npm install
      - npm run build
      - cd ../../
      - echo "React App build completed."

  build:
    commands:
      - echo "CDK Synth..."
      - cd frontend/cdk
      - cdk synth
      - echo "CDK Synth completed."

  post_build:
    commands:
      - echo "Deploying React App with CDK..."
      - cdk deploy --all --require-approval never
      - echo "CDK Deploy completed."

# artifacts:
#   files:
#     - "**/*"
